apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sampleapp
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/small298/SampleApp298.git
    targetRevision: HEAD
    path: k8s-manifests
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

